name: CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'wrapper.py'
      - 'autoprimenet.py'
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  PyInstaller:
    name: Windows PyInstaller

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.4", "3.8", "3.13", "3.x"]
        architecture: ["x86", "x64"]
        include:
          - os: windows-11-arm
            python-version: "3.x"
            architecture: "arm64"
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      if: ${{ matrix.python-version != '3.4' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests pyinstaller
    - name: Install dependencies
      if: ${{ matrix.python-version == '3.4' }}
      run: |
        python -m pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --upgrade pip==19.3
        python -m pip install --ignore-requires-python certifi==2021.10.8 urllib3==1.26.16 idna==3.1 requests[use_chardet_on_py3]==2.26.0 pefile==2019.4.18 pywin32-ctypes==0.2.0 pyinstaller==3.5
    - name: Script
      run: |
        python -X dev autoprimenet.py --help
        curl -sSfO https://www.mersenne.org/favicon.ico
        python -OO -m PyInstaller -F -n autoprimenet -i favicon.ico wrapper.py
        .\dist\autoprimenet --help
    - uses: actions/upload-artifact@v5
      with:
        name: AutoPrimeNet_Windows${{ matrix.python-version == '3.4' && '-XP' || matrix.python-version == '3.8' && '-Vista-7-8' || matrix.python-version == '3.13' && '-8.1' || '' }}_${{ matrix.architecture }}
        path: |
          README.md
          LICENSE
          dist/*

  deploy:
    name: Windows Deploy
    needs: PyInstaller

    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v6
    - name: Install
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lftp
    - name: Script
      run: |
        set -x
        ls -alR AutoPrimeNet_Windows*
        for DIR in AutoPrimeNet_Windows*/; do (cd "$DIR"; zip -j "../${DIR%/}.zip" -- README.md LICENSE dist/*); done
        ls -alR AutoPrimeNet_Windows*
        lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" -e "set ssl:verify-certificate false; mput AutoPrimeNet_Windows*.zip; exit" download.mersenne.ca
